source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
gem 'sprockets-traceur', path: '../..'
gem 'traceur-rb', path: '../../../traceur-rb'
